export {
  ZCODE_EXTENSION_API_VERSION,
  defineMainExtension,
  type ExtensionActivationResult,
  type ExtensionCapability,
  type ExtensionContext,
  type ExtensionDisposable,
  type ExtensionHostCapabilities,
  type ExtensionLogger,
  type ExtensionManifest,
  type ExtensionModule,
  type ExtensionTaskRunHandle,
  type ExtensionTaskSpec,
  type ExtensionZCodeApi,
  type ModelRequestEvent,
  type ModelRequestHistory,
  type ModelRequestRecord,
  type ModelTokenUsage,
  type ZCodeMcpServerStatus,
  type ZCodeMessage,
  type ZCodeModelGenerationResult,
  type ZCodeProviderDescriptor,
  type ZCodeProviderRegistry,
  type ZCodeSessionEvent,
  type ZCodeSessionSummary,
  type ZCodeSessionTarget,
  type ZCodeTaskListResult,
  type ZCodeTaskSummary,
  type ZCodeWorkspaceDefaults,
  type ZCodeWorkspaceTarget,
} from "./index.js";
