import type * as Sdk from "./index.js";

export const UI_CONTRIBUTION_SLOTS = [
  "sidebar.navigation",
  "workspace.header.actions",
  "task.row.trailing",
  "chat.header.actions",
  "chat.overlay",
  "chat.composer.leading",
  "chat.composer.trailing",
  "chat.turn.after",
  "chat.message.before",
  "chat.message.after",
  "chat.message.footer",
  "chat.message.overlay",
] as const;

export function defineRendererExtension(extension: Sdk.RendererExtension): Sdk.RendererExtension {
  return extension;
}

export type {
  ActiveUiContext,
  CheckpointEventPayload,
  ExtensionActivationResult,
  ExtensionBridge,
  ExtensionCapability,
  ExtensionDisposable,
  ExtensionHostCapabilities,
  ExtensionManifest,
  ExtensionModelRef,
  ExtensionTaskResult,
  ExtensionTaskResultStatus,
  ExtensionTaskRunHandle,
  ExtensionTaskSpec,
  ExtensionZCodeApi,
  InteractionEventPayload,
  KnownZCodeSessionEvent,
  KnownZCodeSessionEventName,
  KnownZCodeSessionEventPayloads,
  MessageEventPayload,
  ModelCallSource,
  ModelRequestEvent,
  ModelRequestHistory,
  ModelRequestRecord,
  ModelStreamingPayload,
  ModelTokenUsage,
  PartEventPayload,
  RecoveryEventPayload,
  RendererExtension,
  RendererExtensionContext,
  SessionEventPayload,
  SessionLifecyclePayload,
  ToolEventPayload,
  TurnEventPayload,
  UiContributionMount,
  UiContributionSlot,
  UnknownZCodeSessionEvent,
  ZCodeMcpServerStatus,
  ZCodeMessage,
  ZCodeModelGenerationResult,
  ZCodeProviderDescriptor,
  ZCodeProviderRegistry,
  ZCodeSessionEvent,
  ZCodeSessionSummary,
  ZCodeSessionTarget,
  ZCodeStreamEnvelope,
  ZCodeSubscriptionTarget,
  ZCodeTaskListResult,
  ZCodeTaskSummary,
  ZCodeWorkspaceDefaults,
  ZCodeWorkspaceTarget,
} from "./index.js";
